version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_sailingloc
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - sailingLocNet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sailingloc-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev 
    networks:
      - sailingLocNet

networks:
  sailingLocNet:

volumes:
  mongo_data:
